services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            FRONTEND_URL: '${FRONTEND_URL}'
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
            APP_ENV: '${APP_ENV:-local}'
            OCTANE_SERVER: frankenphp
            DB_HOST: pgsql
            DB_PORT: 5432
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - '.:/app'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis

    pgsql:
        image: 'postgres:17-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        networks:
            - sail
        depends_on:
            - pgsql

    redis:
        image: redis:alpine
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
