name: Deploy Laravel Dockerized App

on:
  push:
    branches:
      - main   # Deploy only when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "👉 Pulling latest code"
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch --all
            git reset --hard origin/main

            echo "👉 Rebuilding Docker containers"
            docker compose down
            docker compose up -d --build

            echo "👉 Running Laravel maintenance tasks"
            # Run inside the app container (adjust container name if different)
            docker exec app php artisan migrate --force
            docker exec app php artisan optimize
            docker exec app php artisan storage:link || true

            echo "👉 Restarting queue workers (if any)"
            docker exec app php artisan queue:restart || true

            echo "👉 Cleaning up Docker junk"
            docker system prune -f
